# Generated by Django 3.2.9 on 2021-11-22 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('house_detail', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rent', models.IntegerField()),
                ('house_detail', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
